apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dx2oxdh8f-nodejs 
  janus-idp.io/tekton: dx2oxdh8f-nodejs
  backstage.io/kubernetes-id: dx2oxdh8f-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dx2oxdh8f-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml